version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.15.0
        steps:
            - checkout
            - restore_cache:
                  name: Restoring dependencies
                  keys:
                      - dependencies-v1-{{ checksum "yarn.lock" }}
            - run:
                  name: Installing dependencies
                  command: yarn
            - save_cache:
                  name: Saving dependencies
                  paths:
                      - ~/.cache/yarn
                      - node_modules
                  key: dependencies-v1-{{ checksum "yarn.lock" }}
            - run:
                  name: Running tests
                  command: yarn test
